In [ ]:
import torch
import time

In [ ]:
# Question 1

# My solution
x = torch.full((13,13), 1)
x[1,:] = 2
x[6,:] = 2
x[11,:] = 2

x[:,2] = 2
x[:,6] = 2
x[:,11] = 2

x[3:5, 3:5] = 3
x[8:10, 8:10] = 3
x[8:10, 3:5] = 3
x[3:5, 8:10] = 3

print(x)

tensor([[1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 1, 2, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 1, 2, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 1, 2, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 1, 2, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])


In [ ]:
# Solution provided by Mustafa hoca 

x = torch.full((13, 13), 1)
x[1::5,:] = 2
x[:, 1::5] = 2
x[3::5,3::5] = 3
x[3::5,4::5] = 3
x[4::5,3::5] = 3
x[4::5,4::5] = 3
x

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

In [ ]:
# Solution found from github

m = torch.full((13, 13), 1.0, dtype = torch.int8)

m[3:5, 3:5] = 3
m[8:10, 3:5] = 3
m[3:5, 8:10] = 3
m[8:10, 8:10] = 3

m[:, 1::5] = 2
m[1::5, :] = 2

print(m)

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]], dtype=torch.int8)


In [ ]:
# Question 2

M = torch.empty(20,20).normal_()
inv_M = M.inverse()
x = torch.diag(torch.arange(1,21,1), diagonal=0)
print(x.size())

x = x.float()

temp = torch.mm(inv_M , x)
temp = torch.mm(temp, M)
result, _ = torch.eig(temp)

print(result[:,0])


torch.Size([20, 20])
tensor([20.0000, 19.0000,  1.0000,  2.0000,  3.0000,  4.0000, 18.0000, 17.0000,
        16.0000,  5.0000, 15.0000,  6.0000, 14.0000,  7.0000,  8.0000, 13.0000,
        12.0000,  9.0000, 10.0000, 11.0000])


In [ ]:
# Solution provided by Mustafa hoca

M = torch.empty(20, 20).normal_()
D = torch.diag(torch.arange(1, 21, dtype=torch.float))
A = torch.mm(torch.mm(torch.inverse(M), D), M)
e, _ = torch.eig(A)
e[:,0]

tensor([20.0000, 19.0000, 18.0000,  1.0000,  2.0001, 17.0000,  3.0000, 16.0000,
         4.0000, 15.0000, 14.0000, 13.0000, 11.9999,  5.0000,  6.0000,  7.0000,
        11.0000, 10.0000,  8.0000,  9.0000])

In [ ]:
 # Question 3
  
import time

M1 = torch.empty(5000,5000).normal_()
M2 = torch.empty(5000,5000).normal_()

start = time.perf_counter()
product = torch.mm(M1, M2)
end = time.perf_counter()

dt = end - start
print(dt)

print('Elapsed time is {:.2f} sec. / {:.2f} GFLOPS'.format(dt, 5000 ** 3 / dt / 1e9)) ## I took this line from the solution given by Mustafa hoca 

3.671342400999947
Elapsed time is 3.67 sec. / 34.05 GFLOPS


In [ ]:
# solution from github for the estimating floating point products have been executed per second

result = (M1.size(0)**3 ) / dt
print(result / 1000000000) # 1 gigaFLOPS (GFLOPS) means 10^9 floating-point operations per second. 

34.23470760438363


In [ ]:
# Solution provided by Mustafa hoca

n = 5000
A = torch.empty(n, n).normal_()
B = torch.empty(n, n).normal_()
start = time.perf_counter()
C = torch.mm(A, B)
stop = time.perf_counter()
dt = stop - start
print('Elapsed time is {:.2f} sec. / {:.2f} GFLOPS'.format(dt, n ** 3 / dt / 1e9))

Elapsed time is 3.71 sec. / 33.69 GFLOPS


In [ ]:
# My solution

def mul_row(tensor_2d):
  for i in range(1, tensor_2d.size(0) ): # list(tensor_2d.size())[0]
    #tensor_2d[i] *= i+1
    for j in range(0,tensor_2d.size(1)):
      tensor_2d[i][j] *= i+1 
  return tensor_2d

m = torch.full((4, 8), 2.0)
m

mul_row(m) 

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
m = torch.full((4, 8), 2.0)
m

def mul_row_fast(tensor_2d):
  coef = torch.arange(1,tensor_2d.size(0)+1,1).float()
  # torch.unsqueeze: Returns a new tensor with a dimension of size one inserted at the specified position. 1 -> as column, 0 -> as row
  coef = torch.unsqueeze(coef, 1) 
  tensor_2d = tensor_2d * coef
  #tensor_2d = tensor_2d.view(2,-1)
  return tensor_2d

mul_row_fast(m)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
m = torch.full((1000, 400), 2.0)

start = time.perf_counter()
mul_row(m)
stop = time.perf_counter()
dt1 = stop - start

dt1


3.7848212100002456

In [ ]:
m = torch.full((1000, 400), 2.0)

start = time.perf_counter()
mul_row_fast(m)
stop = time.perf_counter()
dt2 = stop - start

dt2

0.000549476000287541

In [ ]:
if(dt1 > 100 * dt2):
  print("Success!")

Success!


In [ ]:
# Solution from Mustafa hoca

def mul_row(A):
    m, n = A.shape
    B = torch.empty(m, n)
    for i in range(m):
        for j in range(n):
            B[i, j] = (i+1) * A[0, j]
    return B

def mul_row_fast(A):
    m, n = A.shape
    return torch.mul(torch.arange(m)[:, None] + 1, A[0, :])

m = torch.full((1000, 400), 2.0)

start = time.perf_counter()
mul_row(m)
stop = time.perf_counter()
dt1 = stop - start

print(dt1)

m = torch.full((1000, 400), 2.0)

start = time.perf_counter()
mul_row_fast(m)
stop = time.perf_counter()
dt2 = stop - start

print(dt2)

if(dt1 > 100 * dt2):
  print("Success!")

4.461306100999991
0.0005442669998956262
Success!


In [ ]:
# fast mult method found from github

def mul_row_fast(matrix):
    num_of_rows = matrix.size(0)
    new_vec = torch.arange(1, num_of_rows + 1).float()
    new = new_vec.view( num_of_rows,1  )
    result = matrix.mul(  new)
    return result

m = torch.full((1000, 400), 2.0)

start = time.perf_counter()
mul_row_fast(m)
stop = time.perf_counter()
dt2 = stop - start

dt2

0.0006213289998413529

In [ ]:
# Ek bilgi

x = torch.arange(8) # 1 row matrix
x[:, None] # torch.arange(8)[:, None] # to convert it to column matrix

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]])